### ISSUE TITLE
Mengapa front-end tidak bisa dijalankan di laptop saya?

### ISSUE THREAD

**Issue by NuhShh** [Kelompok7PBO4609/TubesPBOKelompok7-SwanLake-Tech-#4]
Saya sudah mencoba untuk menjalankan front end tetapi tidak bisa.

saya sudah membuka foldernya dan npm start di terminal tapi tidak bisa berjalan, bagaimana caranya bang?

![{8927AD29-2A02-4289-BB84-35D45E6790C7}](https://github.com/user-attachments/assets/48d15e19-3114-4709-a420-eee62882a97b)

Ini isi dari front end yg saya download dari github
![{4919B14F-0EEF-4F50-A728-77E30F708F93}](https://github.com/user-attachments/assets/5aaaa70e-8c11-4600-a1cf-4f85e2e4f515)

![maxresdefault](https://github.com/user-attachments/assets/f694cd7b-8135-4bbc-a778-ff13b0c80664)

**Comment by dzooeel** [comment]
sepertinya karena npmnya belum anda install kawan
